schemaVersion: 1
app: nginx-exporter
kind: niceos-application-container
sourceOfTruth:
  type: git
  url: https://specs.niceos.ru/niceos-containers/app-nginx-exporter
  branch: main
  tag: v1.5.1-niceos13-r2
  buildSourceCommit: a3624a1dcdf2d6cbfcc82c4b8fa193b5412e9822
  metadataCommit: pending
publicMonorepo:
  type: git
  url: https://github.com/niceos-containers/containers
  path: apps/nginx-exporter
images:
  dockerHub:
    registry: docker.io
    namespace: niceos
    repository: nginx-exporter
    image: docker.io/niceos/nginx-exporter
    tags:
      - 1.5.1-niceos13-r2
      - "1.5.1"
      - latest
    digest: sha256:47c616989ca204f5d3e5b0c5d321b37be7d175368a8b7dfbb228fad9edcec5ad
    signed: false
  ghcr:
    registry: ghcr.io
    namespace: niceos-containers
    repository: nginx-exporter
    image: ghcr.io/niceos-containers/nginx-exporter
    tags:
      - 1.5.1-niceos13-r2
      - "1.5.1"
      - latest
    digest: sha256:47c616989ca204f5d3e5b0c5d321b37be7d175368a8b7dfbb228fad9edcec5ad
    signed: false
base:
  image: docker.io/niceos/niceos-container-base
  tag: 13
  ref: docker.io/niceos/niceos-container-base:13
runtime:
  niceosContainer: "13"
  nginx-exporter: "1.5.1"
compatibility:
  mode: bitnami-compatible-migration-target
  reference: bitnami/nginx-exporter/1/debian-12
sync:
  mode: release
  generatedBy: niceos_app_release.py
  generatedAt: 2026-06-08T21:42:31Z
