schemaVersion: 1
app: nginx-exporter
kind: niceos-application-container
sourceOfTruth:
  type: git
  url: https://specs.niceos.ru/niceos-containers/app-nginx-exporter
  branch: main
  tag: v1.5.1-niceos13-r2
  buildSourceCommit: 4a5257f73d8fdad4952747bd33f9476709002c55
  metadataCommit: pending
publicMonorepo:
  type: git
  url: https://github.com/niceos-containers/containers
  path: apps/nginx-exporter
images:
  dockerHub:
    registry: docker.io
    namespace: niceos
    repository: nginx-exporter
    image: docker.io/niceos/nginx-exporter
    tags:
      - 1.5.1-niceos13-r2
      - "1.5.1"
      - latest
    digest: sha256:6b5c5f52cae3acb4ada82dc1a3903fd36596dfa7e09d23425186a2f424809430
    signed: false
  ghcr:
    registry: ghcr.io
    namespace: niceos-containers
    repository: nginx-exporter
    image: ghcr.io/niceos-containers/nginx-exporter
    tags:
      - 1.5.1-niceos13-r2
      - "1.5.1"
      - latest
    digest: sha256:6b5c5f52cae3acb4ada82dc1a3903fd36596dfa7e09d23425186a2f424809430
    signed: false
base:
  image: docker.io/niceos/niceos-container-base
  tag: 13
  ref: docker.io/niceos/niceos-container-base:13
runtime:
  niceosContainer: "13"
  nginx-exporter: "1.5.1"
compatibility:
  mode: bitnami-compatible-migration-target
  reference: bitnami/nginx-exporter/1/debian-12
sync:
  mode: release
  generatedBy: niceos_app_release.py
  generatedAt: 2026-06-08T22:08:50Z
