schemaVersion: 1
app: git
kind: niceos-application-container
sourceOfTruth:
  type: git
  url: https://specs.niceos.ru/niceos-containers/app-git
  branch: main
  tag: 
  buildSourceCommit: 33da03c58d3d59e5918c79b985bc6705d92c4d53
  metadataCommit: 61e5be8df010bd2a7471c78caa9f3f623457ee8e
publicMonorepo:
  type: git
  url: https://github.com/niceos-containers/containers
  path: apps/git
images:
  dockerHub:
    registry: docker.io
    namespace: niceos
    repository: git
    image: docker.io/niceos/git
    tags:
      - 2.54.0-niceos13-r2
      - "2.54.0"
      - latest
    digest: sha256:612d39a6aa268a379e938bf7695d312b78ea7e522ead5779ce9ee5e0216fba0d
    signed: true
  ghcr:
    registry: ghcr.io
    namespace: niceos-containers
    repository: git
    image: ghcr.io/niceos-containers/git
    tags:
      - 2.54.0-niceos13-r2
      - "2.54.0"
      - latest
    digest: sha256:612d39a6aa268a379e938bf7695d312b78ea7e522ead5779ce9ee5e0216fba0d
    signed: true
runtime:
  niceosContainer: "13"
  git: "2.54.0"
  gitLfs: "3.7.1"
compatibility:
  mode: bitnami-compatible-migration-target
  reference: bitnami/git/2/debian-12
sync:
  mode: update
  generatedBy: niceos_app_git_release_v2.py
  generatedAt: 2026-06-05T13:51:04Z
