worker_processes auto;

error_log  /opt/bitnami/nginx/logs/error.log warn;
pid        /opt/bitnami/nginx/tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log /opt/bitnami/nginx/logs/access.log;

    sendfile on;
    keepalive_timeout 65;

    client_body_temp_path /opt/bitnami/nginx/tmp/client_body_temp;
    proxy_temp_path       /opt/bitnami/nginx/tmp/proxy_temp;
    fastcgi_temp_path     /opt/bitnami/nginx/tmp/fastcgi_temp;
    uwsgi_temp_path       /opt/bitnami/nginx/tmp/uwsgi_temp;
    scgi_temp_path        /opt/bitnami/nginx/tmp/scgi_temp;

    include /opt/bitnami/nginx/conf/server_blocks/*.conf;
}
